trigger:
  - main

pool:
  name: 'exp10' # Your self-hosted agent pool name

steps:
  - checkout: self
    displayName: 'Checkout Code from GitHub'

  - script: mvn clean test
    displayName: 'Build and Run Unit Tests'
    workingDirectory: 'maven/myapp'

  # Step 3: Publish Test Results (JUnit)
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
      testResultsFormat: 'JUnit'
      failTaskOnMissingResultsFile: true
    displayName: 'Publish Maven Test Results'

  # Step 4: Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'
